# Generated by Django 4.0.5 on 2022-06-06 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('alfa romeo', 'Alfa Romeo'), ('audi', 'Audi'), ('b.m.w.', 'B.M.W'), ('dacia', 'Dacia'), ('fiat', 'Fiat'), ('ford', 'Ford'), ('honda', 'Honda'), ('mercedez-benz', 'Mercedez-Benz'), ('opel', 'Opel'), ('peugeot', 'Peugeot'), ('renault', 'Renault'), ('seat', 'Seat'), ('skoda', 'Skoda'), ('smart', 'Smart'), ('toyota', 'Toyota'), ('volkswagen', 'Volkswagen'), ('other', 'Other')], max_length=20)),
                ('type_of_car', models.CharField(default='', max_length=30)),
                ('num_plate', models.CharField(max_length=15)),
                ('engine_size', models.IntegerField()),
                ('year', models.IntegerField()),
                ('is_electric', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
